runtime: python311
instance_class: F2

env_variables:
  BUCKET_NAME: "staging.sparks-web-test.appspot.com"

handlers:
- url: /(.*\.(css|js|gif|png|jpg|ico|svg|woff2|ttf|eot))$
  static_files: static/\1
  upload: static/.*\.(css|js|gif|png|jpg|ico|svg|woff2|ttf|eot)$

- url: /(.*\.(html|htm|yaml|txt))$
  static_files: \1
  upload: .*\.(html|htm|yaml|txt)$

- url: /.*
  secure: always
  redirect_http_response_code: 301
  static_files: sparks-web-test/src/index.html
  upload: sparks-web-test/src/index.html
  expiration: "1m"
