runtime: python39
api_version: 1
threadsafe: true


handlers:
  - url: /
    static_files: sparks-web-test/src/index.html
    upload: sparks-web-test/src/index.html

  - url: /.*
    static_dir: sparks-web-test
